<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Tuan Linh
 * Date: 2015-11-23
 * Time: 23:37
 */

namespace Antoree\Models\Plugins\ExtraHtml;

use Antoree\Models\Plugins\DefaultWidget\Widget as DefaultWidget;
use Antoree\Models\Themes\LmsThemeFacade;

class Widget extends DefaultWidget
{
    const WIDGET_NAME = 'extra_html';
    const WIDGET_DISPLAY_NAME = 'Extra HTML';

    public $content;

    public function __init()
    {
        parent::__init(); // TODO: Change the autogenerated stub

        $this->content = '';
        if (!empty($this->localizedData)) {
            $this->content = empty($this->localizedData['content']) ? '' : $this->localizedData['content'];
        }
    }

    public function __initAdminViewParams()
    {
        $this->setViewParams([
            'extended_localizing_path' => LmsThemeFacade::commonWidget($this::WIDGET_NAME, 'admin_localizing')
        ]);
    }

    public function render()
    {
        return $this->content;
    }

    public function localizedFields()
    {
        return array_merge(parent::localizedFields(), [
            'content',
        ]);
    }
}