<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Tuan Linh
 * Date: 2015-11-24
 * Time: 14:06
 */

namespace Antoree\Models\Plugins\OwnerInformation;

use Antoree\Models\Themes\Extension as BaseExtension;

class Extension extends BaseExtension
{
    const EXTENSION_NAME = 'owner_information';
    const EXTENSION_DISPLAY_NAME = 'Owner Information';
    const EXTENSION_DESCRIPTION = 'Set up Information about the Owner';
    const EXTENSION_EDITABLE = true;
    const EXTENSION_TRANSLATABLE = true;

    public function __construct()
    {
        parent::__construct();
    }

    public function __init()
    {
        parent::__init(); // TODO: Change the autogenerated stub

        $owner = OwnerInfo::getInstance();
        $owner->name = $this->getProperty('name');
        $owner->description = $this->getProperty('description');
        $owner->logo = $this->getProperty('logo');
        $owner->email = $this->getProperty('email');
        $owner->slogan = $this->getProperty('slogan');
        $owner->tagLine = $this->getProperty('tag_line');
        $owner->brief = $this->getProperty('brief');
        $owner->headOffice = $this->getProperty('head_office');
        $owner->branchOffices = explode(PHP_EOL, $this->getProperty('branch_offices'));
    }

    public function fields()
    {
        return array_merge(parent::fields(), [
            'logo'
        ]);
    }

    public function validationRules()
    {
        return array_merge(parent::validationRules(), [
            'logo' => 'required|url',
        ]);
    }

    public function localizedFields()
    {
        return array_merge(parent::localizedFields(), [
            'name', 'description', 'tag_line', 'slogan', 'brief',
            'head_office', 'branch_offices',
        ]);
    }

    public function localizedValidationRules()
    {
        return array_merge(parent::localizedValidationRules(), [
            'name' => 'required|max:255',
            'tag_line' => 'sometimes|max:255',
            'slogan' => 'sometimes|max:255',
        ]);
    }
}